# Generated by Django 6.0 on 2026-01-13 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_availability'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='availability',
            constraint=models.UniqueConstraint(fields=('service', 'date', 'start_time', 'end_time'), name='uniq_service_date_time_slot'),
        ),
    ]
